FROM rust:1.41-slim

RUN apt-get -y update && apt-get install -y default-libmysqlclient-dev default-mysql-client
RUN cargo install diesel_cli --no-default-features --features mysql
COPY ./migration.sh ./

CMD ./migration.sh
